### ISSUE TITLE
Activation code doesn't work / Build for ARM64?

### ISSUE THREAD

**Issue by jtarvainen** [Misioslav/expressvpn#10]
Hi,

I have an ARM64 device. I built the Docker image on another computer using the parameters:

```
--build-arg PLATFORM=armhf
--platform linux/arm/v7
```

I then ran the container on the ARM64 device, specifying my ExpressVPN activation code in the `CODE` environment variable. I get the expected warning about the platform mismatch ("The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"), but the container starts up nonetheless. However, when looking at the logs, I see the following:

```
Restarting ExpressVPN service: expressvpnd.
spawn expressvpn activate
Enter activation code: 
Activating...
Unable to sign in. Please check your connection and try again.
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.
```

As suggested in the other issue, I checked that the value of $CODE is correct inside the running container.

Any suggestions? Could this be related to the fact that I'm running an ARM v7 build on an ARM64 device? If so, would it be possible to get a build for ARM64?

Thanks!

**Comment by Misioslav** [comment]
As far as I know, it should not be a big deal to run it in such a setup.

I occasionally get such error but usually, after one or two manual container restarts it is fixed.
Personally, I'm not sure why it happens, I never investigated it to such a degree.

You can firstly check inside of your container if `$CODE` has the value expected by you.
Worst-case scenario you can activate it from inside of the container and connect, as you will normally do not restart that container much (if at all) it will hold the connection but like I've said, usually, one or two container restarts does the job.

**Comment by jtarvainen** [comment]
Thanks for the quick reply! It turned out this was a namespace issue; adding the following to the run command helped:

`--net=host`

**Comment by Misioslav** [comment]
Great! Sorry, I couldn't be much of a help.

Will close the issue in that case.

**Comment by jtarvainen** [comment]
Thanks!

**Comment by hald0r** [comment]
Hello! I recently updated to the latest ExpressVPN. After starting the container, I noticed the following terminal message...

"WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

In looking at the Container Log for ExpressVPN, I get the following...

Enter activation code: 
Activating...
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.
Please activate your account.

Trying to figure out what I am possibly doing wrong. The environment is a MacMini M2 with OS 13.3.1. I am still learning my way around docker/portainer so please forgive if the answer may be obvious. Thank you for any guidance!
