### ISSUE TITLE
Unable to connect to any location - Synology DSM 7.0.1-42218 Update 2

### ISSUE THREAD

**Issue by beastlyDartfordian** [Misioslav/expressvpn#15]
Hey,

I had some issues with my raspberry pi corrupting (unrelated to this project) so I figured I'd host some of my containers on my Synology NAS. 

However I can't seem to connect to any location, it seems to activate fine, start going through the connection process before dropping before connection is complete.
![image](https://user-images.githubusercontent.com/12050240/175666095-b78e62d6-a2d2-45c8-a64e-d5d2ab278adc.png)

Here is my docker compose
expressvpn:
  image: misioslav/expressvpn:latest
  container_name: expressvpn_denmark
  restart: unless-stopped
  ports: # ports from which container that uses expressvpn connection will be available in local network
    - 8001:8989
    - 8002:7878
    - 8003:8686
    - 8004:9696
    - 8005:8005
    - 8006:8006
    - 8007:6881
    - 8008:8080
  environment:
    - WHITELIST_DNS=1.1.1.1,8.8.8.8  # Comma seperated list of dns servers you wish to use and whitelist via iptables
    - CODE=E*****O # Activation Code from ExpressVPN https://www.expressvpn.com/support/troubleshooting/find-activation-code/
    - SERVER=dk # By default container will connect to smart location, list of available locations you can find below
    - DDNS=b*****g # optional
    - NETWORK=on #optional and set to on by default
    - PROTOCOL=lightway_udp #optional set default to lightway_udp see protocol and cipher section for more information
    - CIPHER=chacha20 #optional set default to chacha20 see protocol and cipher section for more information    
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  stdin_open: true
  tty: true
  command: /bin/bash
  privileged: true

Figuring this is a synology related issue as I've basically been running this same setup on raspberry pi (except for specific image) no problem, but if anyone has any suggestions that would be appreciated.

**Comment by Misioslav** [comment]
Hey

please try this script https://github.com/Misioslav/expressvpn/issues/11#issuecomment-1003757934 and please let me know if it helped

**Comment by beastlyDartfordian** [comment]
Took me a moment to figure out how to run the script on dsm, but eventually managed to and it has worked.

Thank-you for the guidance!

![image](https://user-images.githubusercontent.com/12050240/175699891-c5f06884-396a-48db-a8bf-ba346c59ce1f.png)

**Comment by beastlyDartfordian** [comment]
Apologies for re-opening
