### ISSUE TITLE
Leaking Original IP

### ISSUE THREAD

**Issue by realdeeguy** [Misioslav/expressvpn#17]
I have 2 other dockers that are dependent on this express vpn docker and everytime I restart this VPN docker, this and other dependent dockers are leaking/using the actual IP and not the VPN IP for few seconds before it gets the VPN IP

**Comment by realdeeguy** [comment]
Thanks for your reply.

This is the current config status. Please suggest if I am checking this correctly ?

![image](https://user-images.githubusercontent.com/68801231/190672211-15cfd205-2c42-449f-8246-b73cdc3dd45c.png)

**Comment by Misioslav** [comment]
By default this docker has `network_lock` set to `on` but I've added a script to the starting procedure to check the kernel version and if need be to show information that `network_lock` is not supported on this kernel version.
Can you check the logs of your docker if you have such information?

You can also do the following command to set the expressvpn `network_lock` to `on`.
`expressvpn preferences set network_lock on` <- execute this from inside the container.

There is also a possibility the min kernel version to support it has changed.

**Comment by realdeeguy** [comment]
when I set the NETWORK variable to OFF it shows as off in the command line and when i set it to ON it shows as Default

**Comment by Misioslav** [comment]
Do you have in your compose file `network_mode` and `depends_on` set for the other two dockers?
For example, it may look like this:
```
    network_mode: service:expressvpn
    depends_on:
      - expressvpn
```
That's the only other thing that comes to my mind.
