### ISSUE TITLE
Mikrotik Assistance

### ISSUE THREAD

**Issue by haydenbarkernz** [Misioslav/expressvpn#18]
Hi there,

I'm trying to run this on a mikrotik instance and having some real trouble getting my activation code into the docker. It won't let me enter it at the point of 'expressvpn activate' and I have tried all sorts of environment variables to get the code in that way (CODE, ACTIVATION_CODE, ENV CODE) but no luck. I'm new to containers in general so I'm sure this is my fault. Any chance you can assist ?

**Comment by haydenbarkernz** [comment]
Never mind ! it was a configuration error. I would like to know how to point traffic at this container and have it routed out through the tunnel though. This would turn this container into something really powerful.

**Comment by Misioslav** [comment]
Hi!
If you are using compose you can use the following scheme when setting up containers that should use expressvpn as their gateway to the outside world.

```  
example_container:
    image: maintainer/example:version
	container_name: example
	network_mode: service:expressvpn
	depends_on:
	  - expressvpn
```

If you are not using compose but just standard docker commands this might help:

```
    docker run \
    --name=example \
    --net=container:expressvpn \
    maintainer/example:version
```
