### ISSUE TITLE
raspberry pi version

### ISSUE THREAD

**Issue by LordZeuss** [Misioslav/expressvpn#2]
I am trying to get this setup, and I see you mentioned to add the tag -armhf to be able to run it on raspberry pi, I am new to all of this, and where in the code would I add the tag to be able to run it on a raspberry?

**Comment by Misioslav** [comment]
Hey, so when you are creating a compose file for example you can set it up as for example:

```
expressvpn:
    image: misioslav/expressvpn:armhf

```
Ive noticed just now there was a typo and I was using -armhf but it should be just armhf or :armhf

**Comment by Misioslav** [comment]
Inactivity for a long time
