### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by HPMSGEN8** [Misioslav/expressvpn#20]
Good day 

I am getting the device issue for dev/net/tun when I try and run the commands.

I am using proxmox with a docker container and portainer.

This is my first setup. 

I am not sure how to solve this.

Thanks

**Comment by Misioslav** [comment]
Hey,

I had an issue with dev/net/tun a couple of times and usually the following script helped.

https://github.com/Misioslav/expressvpn/issues/11#issuecomment-1003757934

Unfortunately, I did not use proxmox yet, but if I understand correctly you should be able to log in to the virtual machine and use the script from the link then run docker container.

**Comment by HPMSGEN8** [comment]
Thanks a lot will give this a try and report back.

**Comment by HPMSGEN8** [comment]
That did not work I tried to split it up and that mknod command will not work on my docker.

**Comment by Misioslav** [comment]
In my case, I was running the script on my host machine, but in your case host machine for docker would be a virtual machine on which you run the docker container. If you run the script on the virtual machine (host) and it did not work I might not be able to help, I don't know much about proxmox.

**Comment by HPMSGEN8** [comment]
Thanks will have to google some
More on this and see how to fix it.

Maybe I will try an Ubuntu Server with docker and see.

Thanks again.

**Comment by Misioslav** [comment]
Good luck and please, let me know how you solved the issue!
