### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by RichBrew** [Misioslav/expressvpn#21]
Can you add ping to the base image? I prefer to use something like this for health:

    healthcheck:
      test: "ping -c 1 -I tun0 www.google.com || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3

I can install ping easily enough, but it starts to be a pain doing it every time the container is re-created

**Comment by Misioslav** [comment]
Hey! I think it shouldn't be an issue, but I will be able to do it in a week or so, I won't have access to the computer during this time. If you wish you can make a pull request with the change.

**Comment by Misioslav** [comment]
Took more than a week but the `ping` command should be available within the container.
