### ISSUE TITLE
client container seems to bypass expressvpn

### ISSUE THREAD

**Issue by pmbsa** [Misioslav/expressvpn#22]
Hi, looking for some help. I am using your expressvpn image in a composition. The container that uses the expressvpn service is spinning up fine and ipinfo.io is showing the details as being connected via vpn (basically shows the same as the epressvpn container which is what you would expect). I am using get_iplayer and no matter what I do it seems to somehow bypass the vpn network. I know this because the responses I am getting from iplayer indicate that they are rejecting the requests because of location.. its the oddest thing. I can follow the same model using a nordvpn image and its fine (I need to move off nordvpn as  my subcription is about to expire).  Have you seen anything like this before?

**Comment by Misioslav** [comment]
Hey!

Can you post your compose file or docker set up so I could take a look at that as well?

**Comment by pmbsa** [comment]
the spiplayer service is pretty much an ubuntu image with get_iplayer installed into it. I have a java based UI which goes over the top of it to make it easier to use but the nuts and bolts of it are that its ubuntu with get_iplayer

**Comment by Misioslav** [comment]
From the `docker-compose` file I don't see anything wrong with your approach. My current lead would be that DNS might be leaking which the `iplayer` may be checking. 
Please, remove the `WHITELIST_DNS` from envs and try without it. If that won't work you might want to check the approach from #13 I've placed a script there that Im using. Its being executed by the host machine just in case. I've modified it since then a bit but the general idea is to have the same `resolv.conf` in the `expressvpn` and other images that are using it. In my case, it at least helped with DNS leaking the last time I checked.

**Comment by Misioslav** [comment]
Please, let me know how the above worked and if/when you find a solution for your problem, maybe I will be able to introduce it to the image.

**Comment by pmbsa** [comment]
This is almost certainly an issue with DNS. I am now using an image "qmcgaw/gluetun" which is described as being a vpn "Swiss Army Knife". I stumbled on it trying to find a solution to this. I had exactly the same problem and was advised to disable DOT adn hard wire the VPN dns ip address.. Both of those tings were thankfully easy to do with that image. Just ENV variables but as soon as I did both those things everything worked fine (had to be both). The problem I have is expressvpn wont give me their official dns ip address's, unlike NordVPN but I think I have found it anyway.. Just thought you might be interested to hear.

**Comment by Misioslav** [comment]
So, if I understand correctly, the container you want to use needs to use the same DNS that expressvpn is, if so then basically the script I was referring to from issue #13 might do the trick. The script when executed takes `resolv.conf` values of expressvpn (and its nameserver) and copies it to other containers.
I execute it by cron every 30min or so.
Another approach could be to mount the expressvpn's `resolv.conf` as read-only to containers that will be using expressvpn but the downside of it is that if it changes it won't be updated in other containers.

**Comment by pmbsa** [comment]
just trying the script approach, its seems to be working. Seems a bonkers thing to have to do though, is that just because of how expressvpn works?

**Comment by Misioslav** [comment]
To be honest, I do not know and I was not able so far to figure it out. If you would have ideas for a different approach, please, let me know.
