### ISSUE TITLE
Connect host LAN device to published port?

### ISSUE THREAD

**Issue by vnnegt** [Misioslav/expressvpn#27]
Is there a way to configure the container such that you can connect a LAN device on the host directly to a published port?

Similar to how Gluetun handles it via HTTP proxy: https://github.com/qdm12/gluetun/wiki/Connect-a-LAN-device-to-gluetun

Gluetun isn't playing very nice with ExpressVPN so I'd like to try this tool out, thanks.

**Comment by Misioslav** [comment]
Hey, sorry for late answer.

As far as I have seen it should be doable. It is not implemented in my version but in one of the forks I have seen it: https://github.com/lenuswalker/expressvpn#routing-on-host-machine you can check if it works and if does maybe I will be able to expand the functionality as well.
