### ISSUE TITLE
Error: Could not resolve host

### ISSUE THREAD

**Issue by jaimbox** [Misioslav/expressvpn#28]
This is the error I get... ExpressVPN on it's own does indeed connect to the correct IP as I verified. Transmission, on its own as host connects and works fine but when I change Transmission network to container:expressvpn I get this...

curl ifconfig.io

curl: (6) Could not resolve host: ifconfig.io

**Comment by Misioslav** [comment]
Hey,

The error you are referring to, you are getting from Transmission container?
What's your setup?
