### ISSUE TITLE
Running on RPI with kernel 6.x+ but it says my kernel version is below 4.9

### ISSUE THREAD

**Issue by successtheman** [Misioslav/expressvpn#29]
When starting the container, it says the following

```
Kernel version is lower than the minimum required version (4.9). network_lock will be disabled.
``` 
~~I am going to try [latest-armhf-bookworm](https://hub.docker.com/layers/misioslav/expressvpn/latest-armhf-bookworm/images/sha256-d497750f0f19058b42f4d511b44ab912d695d25dc21368f7aa3afd16e50ed505?context=explore) and see if that helps as I was using latest-armhf before~~ This did not help, and when entering the container cli, the kernel version is 6.1 on armhf-bookworm and latest-armhf, I believe it has something to do with the recent kernel version check you added 

I believe this is where the problem may be https://github.com/Misioslav/expressvpn/blob/3222b215a0ec2426ad6b2bb0a373f25da9c28617/files/uname.sh#L9

In the meantime I have reverted to `3.48.0.4-armhf` instead of the latest version to work around this

**Comment by Misioslav** [comment]
Hey! So it works on 3.48.0.4 version then? If so I will revert the changes I did to uname script in the newset version and rerelease it.

**Comment by successtheman** [comment]
Yes it does work on 3.48.0.4 version without issues, at least it isn't warning about the kernel version, I will verify right now if network lock is actually working by disconnecting VPN and trying to ping some IP addresses

**Comment by successtheman** [comment]
It appears that network_lock is not working even without the kernel warning on 3.48.0.4, as when I disconnected expressvpn in the expressvpn container with `expressvpn disconnect`, I was still able to ping google.com and get a public ip address from `curl icanhazip.com` in another container routed through it so it appears network lock does not work on that version, I will try on the latest version as well now

**Comment by Misioslav** [comment]
When checking please also check expressvpn preferences and check if it actually turned on there if it is it might be connected to something on expressvpn side but I will try to check it soon.

**Comment by Misioslav** [comment]
Ah, you are disconnecting it yourself. It won’t work like that. It’s in case expressvpn itself looses connection and in such time network lock should kick in.

**Comment by successtheman** [comment]
> When checking please also check expressvpn preferences and check if it actually turned on there if it is it might be connected to something on expressvpn side but I will try to check it soon.

```
auto_connect            true
block_trackers          true
desktop_notifications   true
disable_ipv6            true
lightway_cipher         auto
network_lock            default
preferred_protocol      auto
send_diagnostics        false
```

**Comment by successtheman** [comment]
> Ah, you are disconnecting it yourself. It won’t work like that. It’s in case expressvpn itself looses connection and in such time network lock should kick in.

Would there be a way to force it to disconnect? only way I can think of is unplugging ethernet which means I wouldn't be able to control it via ssh to check if there is internet access so it defeats the purpose :joy:

**Comment by Misioslav** [comment]
To be honest, Im not sure, maybe if you are connected and you know the IP of the server you are connected to you can block it on your DNS/router or something which should I think simulates such behavior. But that's me guessing.
