### ISSUE TITLE
Any way to build a socks5 proxy server on this?

### ISSUE THREAD

**Issue by WeishiCheungPDR** [Misioslav/expressvpn#35]
Hello, thanks so much for making this thing, I installed it successfully in my VPS!

**_sorry in advance for asking this stupid question, im still new to this thing_**

but is there a way i can build a socks5 server inside this docker or any other ways?

I want one of my PC to connect to expressvpn from a socks5 proxy

for some reason i cannot just install expressvpn on my machine, and when I install expressvpn in my vps, i lost it forever, cannot ssh to it anymore.

So i think may be this expressvpn running in docker can help me in this case.

any ideas?

**Comment by WeishiCheungPDR** [comment]
i found the way

when create docker, you need to transfer both 80 and 1080(you can change this to whatever port you gonna use for socks server)
run docker
docker exec -it dockerID /bin/bash
sudo apt-get update
sudo apt-get install build-essential git
git clone https://github.com/rofl0r/microsocks.git
cd microsocks
make
nohup ./microsocks -i 0.0.0.0 -p 1080 &
Done.

**Comment by Misioslav** [comment]
Hi, Im sorry for late answer! Im glad you found the solution. If you wish this to become part of the code, feel free to create a PR. I think it could potentially function as optional env.
In Dockerfile we could add `build-essential` and `git` and clone the repo then remove git which will not be needed.
And in the start.sh add procedure to make socks if env is set.
Just an idea.
