### ISSUE TITLE
Feature request:  Add Net-tools

### ISSUE THREAD

**Issue by burnbrigther** [Misioslav/expressvpn#38]
Can we please add net-tools to the image?  Very small and easy to add and gives a lot of tools.  Thank you

**Comment by Misioslav** [comment]
hi! 
We can but what do we want achieve with net-tools?

**Comment by burnbrigther** [comment]
Net-tools add a whole suite of missing, but very useful network troubleshooting tools at the network layer.  Here is the list:
Commands: arp(8)<https://net-tools.sourceforge.io/man/arp.8.html>, hostname(1)<https://net-tools.sourceforge.io/man/hostname.1.html>, ifconfig(8)<https://net-tools.sourceforge.io/man/ifconfig.8.html>, ipmaddr, iptunnel, mii-tool(8)<https://net-tools.sourceforge.io/man/mii-tool.8.html>, nameif(8)<https://net-tools.sourceforge.io/man/nameif.8.html>, netstat(8)<https://net-tools.sourceforge.io/man/netstat.8.html>, plipconfig(8)<https://net-tools.sourceforge.io/man/plipconfig.8.html>, rarp(8)<https://net-tools.sourceforge.io/man/rarp.8.html>, route(8)<https://net-tools.sourceforge.io/man/route.8.html> und slattach(8)<https://net-tools.sourceforge.io/man/slattach.8.html>.

From: Misioslav ***@***.***>
Date: Monday, April 15, 2024 at 12:09 AM
To: Misioslav/expressvpn ***@***.***>
Cc: burnbrigther ***@***.***>, Author ***@***.***>
Subject: Re: [Misioslav/expressvpn] Feature request: Add Net-tools (Issue #38)

hi!
We can but what do we want achieve with net-tools?

**Comment by Misioslav** [comment]
thank you, I just wonder what the container can gain by adding this. Could you elaborate a bit on use case scenarios?

**Comment by burnbrigther** [comment]
Thank you!
