### ISSUE TITLE
docker compose `command` never executes

### ISSUE THREAD

**Issue by benblazak** [Misioslav/expressvpn#41]
Following the example in [polkaned/expressvpn](https://github.com/polkaned/dockerfiles/tree/master/expressvpn), i added

    command: /bin/bash -c "cp /etc/resolv.conf /share/resolv.conf"

to my `compose.yaml` under the `expressvpn` service.

But it looks like this never executes. I think this line might be preventing it

https://github.com/Misioslav/expressvpn/blob/0ee08223c0b193d7b6dd82fbfae89c1a52f12905/files/start.sh#L47

**Comment by Misioslav** [comment]
Hey, yeah it might cause that. Ive added it long time ago due to some other issue.
I will prepare a newer version with those lines removed.

**Comment by Misioslav** [comment]
@benblazak the newest version has been pushed. Please, check it and let me know.

**Comment by benblazak** [comment]
@Misioslav thanks! -- testing

now the container restarts in a loop with the message

    dependency failed to start: container expressvpn is unhealthy

which is strange, because the vpn in the container appears to have started correctly. i wonder if the `healthcheck.sh` is working correctly. i'm not the most familiar with docker, so i'll have to see how deep i'm able to look into this.

**Comment by benblazak** [comment]
thanks for checking :) -- got it working! -- turns out i didn't understand docker -- i was letting the `command` in my `compose.yaml` exit (i understand why there's a call to `bash` at the end in the example now), and i had taken out the `tty: true` option.

the command to copy `resolv.conf` works now too, thanks :)

if i set an invalid `CODE`, it still gives the client container access to the host network though. setting `IP` or `DDNS` is probably a better option, but since those are optional, do you think it would be good to change

https://github.com/Misioslav/expressvpn/blob/5245f4c4cd7415f3e6c3635272672d0110c9dbac/files/start.sh#L38

to

```bash
expressvpn connect $SERVER || exit
```

?

either way, thanks for the help, and thanks for making this container!
