### ISSUE TITLE
After updating to latest version I have issues with network lock

### ISSUE THREAD

**Issue by c0d3x** [Misioslav/expressvpn#5]
Having difficulties getting the latest docker container running in Portainer to work.
Any clues?

`
Restarting ExpressVPN service: expressvpnd.
spawn expressvpn activate

Enter activation code: 
Activating...
Activated.

Help improve ExpressVPN: Share crash reports, speed tests, usability diagnostics, and whether VPN connection attempts succeed. These reports never contain personally identifiable information. (Y/n) network lock mode: default
If your VPN connection unexpectedly drops, internet traffic will now be
blocked by Network Lock to protect your privacy.

Connecting to Smart Location...

Connecting to Germany...
Unable to connect to Germany

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'
`

**Comment by Misioslav** [comment]
Currently, by default network_lock is set to on, you can change it by setting up env NETWORK to off. At least, that worked for me.

**Comment by c0d3x** [comment]
> Currently, by default network_lock is set to on, you can change it by setting up env NETWORK to off. At least, that worked for me.

Yes this worked, I now have connection!
But if VPN connection is now lost, will it use my local IP instead then?
Is there a way to make it connect and also have the network lock?

I am using another port than 80:80, is that why it will not communicate with express with the NETWORK set to on?

**Comment by Misioslav** [comment]
> > Currently, by default network_lock is set to on, you can change it by setting up env NETWORK to off. At least, that worked for me.
> 
> Yes this worked, I now have connection! But if VPN connection is now lost, will it use my local IP instead then? Is there a way to make it connect and also have the network lock?
> 
> I am using another port than 80:80, is that why it will not communicate with express with the NETWORK set to on?

Unfortunately, it will use your local IP.
So far I had no luck with getting it to work with the network_lock set to on, on my machine.

#3 here it worked with network_lock set to on, and so far the only anomaly we could find is the kernel version difference.

What is your kernel version?

**Comment by c0d3x** [comment]
The docker image uses this:
Linux adcb090ff04e 4.4.180+ #42218 SMP Fri Sep 24 02:41:40 CST 2021 x86_64 GNU/Linux

**Comment by Misioslav** [comment]
Actually, docker uses host's kernel.
I have the same version on my Synology NAS and it does not work as well.
I intended to do tests on other versions of Linux to confirm the kernel version theory but I had no time.

**Comment by c0d3x** [comment]
Well that doubles the theory since both use same kernel.
But might be good to try out in another environment, I have docker on my mac and could try it out there.

**Comment by c0d3x** [comment]
Have now tested it on mac with kernel:
Linux 64f266fc32c7 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux

And it works right out of the box! with NETWORK = on

**Comment by Misioslav** [comment]
Thank you for checking!

So it seems the kernel version does not support it. I will have to find the min version of kernel on which network lock works then and add it to the readme

**Comment by Misioslav** [comment]
I couldn't find the information needed anywhere so I reached out to ExpresssVPN support. It seems `network_lock` is supported from Kernel Version 4.9

**Comment by Misioslav** [comment]
In docker container 3.13.0.8 I will add an experimental script that will check if the user's kernel meets minimum requirements and if not and `network_lock` is set to `on` it will disable it with a message and let it run.

Although, I'm not sure if that should stay long-term.

**Comment by Misioslav** [comment]
as it is kernel-based, I will close this issue.
