### ISSUE TITLE
Latest images not allowing dns 

### ISSUE THREAD

**Issue by phynias** [Misioslav/expressvpn#7]
Ever since the latest release no dns traffic works in connected containers. 
I get the following:

```
nslookup google.com
nslookup: write to '1.1.1.1': Operation not permitted
nslookup: write to '1.0.0.1': Operation not permitted
;; connection timed out; no servers could be reached
```
Ping works fine on ip addresses.

If I rollback to 3.10.0.9 everything works fine.
It doesn't appear to be a network lock problem, as I am using the old version with network_lock on and it works fine.
I even tried the newer version with network_lock off and it still did not work.

**Comment by Misioslav** [comment]
I believe the only thing that changed between those versions besides `network_lock` behavior is adding `iptables` which might have impacted it somehow. 
On the other hand on my setup connected containers are able to run `nslookup google.com` command and return a proper response.

```
nslookup google.com
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.208.206
Name:   google.com
Address: 2a00:1450:401b:800::200e
```

What is your setup? Could you share your compose file or commands that you use to run the containers?

**Comment by phynias** [comment]
figured it out.
i was setting the dns servers on the expressvpn container. once i removed them everything worked.

**Comment by Misioslav** [comment]
It seems the issue has been solved.

> i was setting the dns servers on the expressvpn container. once i removed them everything worked.

**Comment by phynias** [comment]
Nope. That's why I deleted that comment.

**Comment by Misioslav** [comment]
My bad then.

Can you provide your `resolv.conf` file before and after connecting to VPN from your expressvpn container?
Also, what's your setup?

Unfortunately, I was not able to reproduce it on my side.

One thing I've added to my compose file for containers that will use expressvpn was:

```
   dns_search:
      - expressvpn
```

Maybe it may help?

**Comment by grburgess** [comment]
I experienced the same issue. The DNS lookup was going nowhere, rolling back to 3.10.0.9 was fine. I also have network_lock working with 3.10.0.9

**Comment by phynias** [comment]
I had to roll my own image add my dns servers to  iptables exception. You
can see it in the default Dockerfile and then just copy it and place in
your own. I can make a pr so it's configurable with an env var.

**Comment by Misioslav** [comment]
> I experienced the same issue. The DNS lookup was going nowhere, rolling back to 3.10.0.9 was fine. I also have network_lock working with 3.10.0.9
> 
> adding dns_search did not help in the latest version.

Thank you for checking!



> I had to roll my own image add my dns servers to iptables exception. You can see it in the default Dockerfile and then just copy it and place in your own. I can make a pr so it's configurable with an env var.

If you could do the pr it would be great!

**Comment by phynias** [comment]
https://github.com/Misioslav/expressvpn/pull/9

**Comment by grburgess** [comment]
Just a note for the future (if someone is as clueless as me)! If you are running your network through a pi-hole and it is serving as your nameserver, add its internal ip to the DNS whitelist. Now that this option exists, all is working for me. Thanks!
